// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckRun } from "./CheckRun";
import type { CiState } from "./CiState";

export type CiStatus = { state: CiState, total_count: number, checks: Array<CheckRun>, };
