// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";
import type { GitHubUser } from "./GitHubUser";
import type { Reactions } from "./Reactions";

export type PrReviewComment = { id: bigint, body: string, path: string, line: number | null, original_line: number | null, side: DiffSide, commit_id: string, user: GitHubUser, created_at: string, updated_at: string, html_url: string, in_reply_to_id: bigint | null, reactions: Reactions | null, };
