// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CiStatus } from "./CiStatus";
import type { GitHubUser } from "./GitHubUser";
import type { Label } from "./Label";
import type { PrState } from "./PrState";

export type PullRequestDetail = { number: bigint, title: string, body: string | null, state: PrState, head_branch: string, base_branch: string, html_url: string, created_at: string, updated_at: string, merged_at: string | null, ci_status: CiStatus | null, user: GitHubUser, additions: number, deletions: number, changed_files: number, mergeable: boolean | null, mergeable_state: string | null, labels: Array<Label>, requested_reviewers: Array<GitHubUser>, draft: boolean, comments_count: number, review_comments_count: number, };
