/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentConfigPermission {
    #[serde(rename = "edit", skip_serializing_if = "Option::is_none")]
    pub edit: Option<Edit>,
    #[serde(rename = "bash", skip_serializing_if = "Option::is_none")]
    pub bash: Option<Box<models::AgentConfigPermissionBash>>,
    #[serde(rename = "skill", skip_serializing_if = "Option::is_none")]
    pub skill: Option<Box<models::AgentConfigPermissionBash>>,
    #[serde(rename = "webfetch", skip_serializing_if = "Option::is_none")]
    pub webfetch: Option<Webfetch>,
    #[serde(rename = "doom_loop", skip_serializing_if = "Option::is_none")]
    pub doom_loop: Option<DoomLoop>,
    #[serde(rename = "external_directory", skip_serializing_if = "Option::is_none")]
    pub external_directory: Option<ExternalDirectory>,
}

impl AgentConfigPermission {
    pub fn new() -> AgentConfigPermission {
        AgentConfigPermission {
            edit: None,
            bash: None,
            skill: None,
            webfetch: None,
            doom_loop: None,
            external_directory: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Edit {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "allow")]
    Allow,
    #[serde(rename = "deny")]
    Deny,
}

impl Default for Edit {
    fn default() -> Edit {
        Self::Ask
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Webfetch {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "allow")]
    Allow,
    #[serde(rename = "deny")]
    Deny,
}

impl Default for Webfetch {
    fn default() -> Webfetch {
        Self::Ask
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DoomLoop {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "allow")]
    Allow,
    #[serde(rename = "deny")]
    Deny,
}

impl Default for DoomLoop {
    fn default() -> DoomLoop {
        Self::Ask
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExternalDirectory {
    #[serde(rename = "ask")]
    Ask,
    #[serde(rename = "allow")]
    Allow,
    #[serde(rename = "deny")]
    Deny,
}

impl Default for ExternalDirectory {
    fn default() -> ExternalDirectory {
        Self::Ask
    }
}

