/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentPartSource {
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "start")]
    pub start: i32,
    #[serde(rename = "end")]
    pub end: i32,
}

impl AgentPartSource {
    pub fn new(value: String, start: i32, end: i32) -> AgentPartSource {
        AgentPartSource { value, start, end }
    }
}
