/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Agent {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "mode")]
    pub mode: Mode,
    #[serde(rename = "native", skip_serializing_if = "Option::is_none")]
    pub native: Option<bool>,
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(rename = "topP", skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "permission")]
    pub permission: Box<models::AgentPermission>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::SessionPromptRequestModel>>,
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(rename = "tools")]
    pub tools: std::collections::HashMap<String, bool>,
    #[serde(rename = "options")]
    pub options: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "maxSteps", skip_serializing_if = "Option::is_none")]
    pub max_steps: Option<i32>,
}

impl Agent {
    pub fn new(
        name: String,
        mode: Mode,
        permission: models::AgentPermission,
        tools: std::collections::HashMap<String, bool>,
        options: std::collections::HashMap<String, serde_json::Value>,
    ) -> Agent {
        Agent {
            name,
            description: None,
            mode,
            native: None,
            hidden: None,
            default: None,
            top_p: None,
            temperature: None,
            color: None,
            permission: Box::new(permission),
            model: None,
            prompt: None,
            tools,
            options,
            max_steps: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "subagent")]
    Subagent,
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "all")]
    All,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Subagent
    }
}
