/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantMessageTokensCache {
    #[serde(rename = "read")]
    pub read: f64,
    #[serde(rename = "write")]
    pub write: f64,
}

impl AssistantMessageTokensCache {
    pub fn new(read: f64, write: f64) -> AssistantMessageTokensCache {
        AssistantMessageTokensCache { read, write }
    }
}
