/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantMessageError {
    #[serde(rename = "name")]
    pub name: Name,
    #[serde(rename = "data")]
    pub data: Box<models::ApiErrorData>,
}

impl AssistantMessageError {
    pub fn new(name: Name, data: models::ApiErrorData) -> AssistantMessageError {
        AssistantMessageError {
            name,
            data: Box::new(data),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "APIError")]
    ApiError,
}

impl Default for Name {
    fn default() -> Name {
        Self::ApiError
    }
}
