/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Auth {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "refresh")]
    pub refresh: String,
    #[serde(rename = "access")]
    pub access: String,
    #[serde(rename = "expires")]
    pub expires: f64,
    #[serde(rename = "enterpriseUrl", skip_serializing_if = "Option::is_none")]
    pub enterprise_url: Option<String>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl Auth {
    pub fn new(
        r#type: Type,
        refresh: String,
        access: String,
        expires: f64,
        key: String,
        token: String,
    ) -> Auth {
        Auth {
            r#type,
            refresh,
            access,
            expires,
            enterprise_url: None,
            key,
            token,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "oauth")]
    Oauth,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "wellknown")]
    Wellknown,
}

impl Default for Type {
    fn default() -> Type {
        Self::Oauth
    }
}
