/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Command {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(rename = "template")]
    pub template: Box<models::CommandTemplate>,
    #[serde(rename = "subtask", skip_serializing_if = "Option::is_none")]
    pub subtask: Option<bool>,
    #[serde(rename = "hints")]
    pub hints: Vec<String>,
}

impl Command {
    pub fn new(name: String, template: models::CommandTemplate, hints: Vec<String>) -> Command {
        Command {
            name,
            description: None,
            agent: None,
            model: None,
            template: Box::new(template),
            subtask: None,
            hints,
        }
    }
}

