/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigTuiScrollAcceleration : Scroll acceleration settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTuiScrollAcceleration {
    /// Enable scroll acceleration
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl ConfigTuiScrollAcceleration {
    /// Scroll acceleration settings
    pub fn new(enabled: bool) -> ConfigTuiScrollAcceleration {
        ConfigTuiScrollAcceleration { enabled }
    }
}
