/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigExperimentalHookFileEditedValueInner {
    #[serde(rename = "command")]
    pub command: Vec<String>,
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<std::collections::HashMap<String, String>>,
}

impl ConfigExperimentalHookFileEditedValueInner {
    pub fn new(command: Vec<String>) -> ConfigExperimentalHookFileEditedValueInner {
        ConfigExperimentalHookFileEditedValueInner {
            command,
            environment: None,
        }
    }
}
