/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigMode : @deprecated Use `agent` field instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigMode {
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<models::AgentConfig>,
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<models::AgentConfig>,
}

impl ConfigMode {
    /// @deprecated Use `agent` field instead.
    pub fn new() -> ConfigMode {
        ConfigMode {
            build: None,
            plan: None,
        }
    }
}

