/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigAgent : Agent configuration, see https://opencode.ai/docs/agent
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAgent {
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<models::AgentConfig>,
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<models::AgentConfig>,
    #[serde(rename = "general", skip_serializing_if = "Option::is_none")]
    pub general: Option<models::AgentConfig>,
    #[serde(rename = "explore", skip_serializing_if = "Option::is_none")]
    pub explore: Option<models::AgentConfig>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<models::AgentConfig>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<models::AgentConfig>,
    #[serde(rename = "compaction", skip_serializing_if = "Option::is_none")]
    pub compaction: Option<models::AgentConfig>,
}

impl ConfigAgent {
    /// Agent configuration, see https://opencode.ai/docs/agent
    pub fn new() -> ConfigAgent {
        ConfigAgent {
            plan: None,
            build: None,
            general: None,
            explore: None,
            title: None,
            summary: None,
            compaction: None,
        }
    }
}
