/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Config {
    /// JSON schema reference for configuration validation
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    /// Theme name to use for the interface
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    #[serde(rename = "keybinds", skip_serializing_if = "Option::is_none")]
    pub keybinds: Option<Box<models::KeybindsConfig>>,
    #[serde(rename = "logLevel", skip_serializing_if = "Option::is_none")]
    pub log_level: Option<models::LogLevel>,
    #[serde(rename = "tui", skip_serializing_if = "Option::is_none")]
    pub tui: Option<Box<models::ConfigTui>>,
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<Box<models::ServerConfig>>,
    /// Command configuration, see https://opencode.ai/docs/commands
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<std::collections::HashMap<String, models::ConfigCommandValue>>,
    #[serde(rename = "watcher", skip_serializing_if = "Option::is_none")]
    pub watcher: Option<Box<models::ConfigWatcher>>,
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<Vec<String>>,
    #[serde(rename = "snapshot", skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<bool>,
    /// Control sharing behavior:'manual' allows manual sharing via commands, 'auto' enables automatic sharing, 'disabled' disables all sharing
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<Share>,
    /// @deprecated Use 'share' field instead. Share newly created sessions automatically
    #[serde(rename = "autoshare", skip_serializing_if = "Option::is_none")]
    pub autoshare: Option<bool>,
    #[serde(rename = "autoupdate", skip_serializing_if = "Option::is_none")]
    pub autoupdate: Option<Box<models::ConfigAutoupdate>>,
    /// Disable providers that are loaded automatically
    #[serde(rename = "disabled_providers", skip_serializing_if = "Option::is_none")]
    pub disabled_providers: Option<Vec<String>>,
    /// When set, ONLY these providers will be enabled. All other providers will be ignored
    #[serde(rename = "enabled_providers", skip_serializing_if = "Option::is_none")]
    pub enabled_providers: Option<Vec<String>>,
    /// Model to use in the format of provider/model, eg anthropic/claude-2
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// Small model to use for tasks like title generation in the format of provider/model
    #[serde(rename = "small_model", skip_serializing_if = "Option::is_none")]
    pub small_model: Option<String>,
    /// Default agent to use when none is specified. Must be a primary agent. Falls back to 'build' if not set or if the specified agent is invalid.
    #[serde(rename = "default_agent", skip_serializing_if = "Option::is_none")]
    pub default_agent: Option<String>,
    /// Custom username to display in conversations instead of system username
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::ConfigMode>,
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<models::ConfigAgent>,
    /// Custom provider configurations and model overrides
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<std::collections::HashMap<String, models::ProviderConfig>>,
    /// MCP (Model Context Protocol) server configurations
    #[serde(rename = "mcp", skip_serializing_if = "Option::is_none")]
    pub mcp: Option<std::collections::HashMap<String, models::McpAddRequestConfig>>,
    #[serde(rename = "formatter", skip_serializing_if = "Option::is_none")]
    pub formatter: Option<Box<models::ConfigFormatter>>,
    #[serde(rename = "lsp", skip_serializing_if = "Option::is_none")]
    pub lsp: Option<Box<models::ConfigLsp>>,
    /// Additional instruction files or patterns to include
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<Vec<String>>,
    #[serde(rename = "layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<models::LayoutConfig>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Box<models::AgentConfigPermission>>,
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<std::collections::HashMap<String, bool>>,
    #[serde(rename = "enterprise", skip_serializing_if = "Option::is_none")]
    pub enterprise: Option<Box<models::ConfigEnterprise>>,
    #[serde(rename = "compaction", skip_serializing_if = "Option::is_none")]
    pub compaction: Option<Box<models::ConfigCompaction>>,
    #[serde(rename = "experimental", skip_serializing_if = "Option::is_none")]
    pub experimental: Option<Box<models::ConfigExperimental>>,
}

impl Config {
    pub fn new() -> Config {
        Config {
            dollar_schema: None,
            theme: None,
            keybinds: None,
            log_level: None,
            tui: None,
            server: None,
            command: None,
            watcher: None,
            plugin: None,
            snapshot: None,
            share: None,
            autoshare: None,
            autoupdate: None,
            disabled_providers: None,
            enabled_providers: None,
            model: None,
            small_model: None,
            default_agent: None,
            username: None,
            mode: None,
            agent: None,
            provider: None,
            mcp: None,
            formatter: None,
            lsp: None,
            instructions: None,
            layout: None,
            permission: None,
            tools: None,
            enterprise: None,
            compaction: None,
            experimental: None,
        }
    }
}
/// Control sharing behavior:'manual' allows manual sharing via commands, 'auto' enables automatic sharing, 'disabled' disables all sharing
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Share {
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Share {
    fn default() -> Share {
        Self::Manual
    }
}
