/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigWatcher {
    #[serde(rename = "ignore", skip_serializing_if = "Option::is_none")]
    pub ignore: Option<Vec<String>>,
}

impl ConfigWatcher {
    pub fn new() -> ConfigWatcher {
        ConfigWatcher { ignore: None }
    }
}
