/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigExperimentalHook {
    #[serde(rename = "file_edited", skip_serializing_if = "Option::is_none")]
    pub file_edited: Option<
        std::collections::HashMap<String, Vec<models::ConfigExperimentalHookFileEditedValueInner>>,
    >,
    #[serde(rename = "session_completed", skip_serializing_if = "Option::is_none")]
    pub session_completed: Option<Vec<models::ConfigExperimentalHookFileEditedValueInner>>,
}

impl ConfigExperimentalHook {
    pub fn new() -> ConfigExperimentalHook {
        ConfigExperimentalHook {
            file_edited: None,
            session_completed: None,
        }
    }
}
