/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigLspAnyOfValueAnyOf1 {
    #[serde(rename = "command")]
    pub command: Vec<String>,
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Vec<String>>,
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "initialization", skip_serializing_if = "Option::is_none")]
    pub initialization: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ConfigLspAnyOfValueAnyOf1 {
    pub fn new(command: Vec<String>) -> ConfigLspAnyOfValueAnyOf1 {
        ConfigLspAnyOfValueAnyOf1 {
            command,
            extensions: None,
            disabled: None,
            env: None,
            initialization: None,
        }
    }
}
