/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigProviders200Response {
    #[serde(rename = "providers")]
    pub providers: Vec<models::Provider>,
    #[serde(rename = "default")]
    pub default: std::collections::HashMap<String, String>,
}

impl ConfigProviders200Response {
    pub fn new(
        providers: Vec<models::Provider>,
        default: std::collections::HashMap<String, String>,
    ) -> ConfigProviders200Response {
        ConfigProviders200Response { providers, default }
    }
}
