/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventVcsBranchUpdatedProperties {
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
}

impl EventVcsBranchUpdatedProperties {
    pub fn new() -> EventVcsBranchUpdatedProperties {
        EventVcsBranchUpdatedProperties { branch: None }
    }
}
