/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMcpToolsChangedProperties {
    #[serde(rename = "server")]
    pub server: String,
}

impl EventMcpToolsChangedProperties {
    pub fn new(server: String) -> EventMcpToolsChangedProperties {
        EventMcpToolsChangedProperties { server }
    }
}
