/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventTodoUpdatedProperties {
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "todos")]
    pub todos: Vec<models::Todo>,
}

impl EventTodoUpdatedProperties {
    pub fn new(session_id: String, todos: Vec<models::Todo>) -> EventTodoUpdatedProperties {
        EventTodoUpdatedProperties {
            session_id,
            todos,
        }
    }
}

