/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventFileWatcherUpdatedProperties {
    #[serde(rename = "file")]
    pub file: String,
    #[serde(rename = "event")]
    pub event: Event,
}

impl EventFileWatcherUpdatedProperties {
    pub fn new(file: String, event: Event) -> EventFileWatcherUpdatedProperties {
        EventFileWatcherUpdatedProperties {
            file,
            event,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "change")]
    Change,
    #[serde(rename = "unlink")]
    Unlink,
}

impl Default for Event {
    fn default() -> Event {
        Self::Add
    }
}

