/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventTodoUpdated {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventTodoUpdatedProperties>,
}

impl EventTodoUpdated {
    pub fn new(r#type: Type, properties: models::EventTodoUpdatedProperties) -> EventTodoUpdated {
        EventTodoUpdated {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "todo.updated")]
    TodoUpdated,
}

impl Default for Type {
    fn default() -> Type {
        Self::TodoUpdated
    }
}

