/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: serde_json::Value,
}

impl Event {
    pub fn new(r#type: Type, properties: serde_json::Value) -> Event {
        Event { r#type, properties }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tui.prompt.append")]
    TuiPromptAppend,
    #[serde(rename = "tui.command.execute")]
    TuiCommandExecute,
    #[serde(rename = "tui.toast.show")]
    TuiToastShow,
    #[serde(rename = "installation.updated")]
    InstallationUpdated,
    #[serde(rename = "installation.update-available")]
    InstallationUpdateAvailable,
    #[serde(rename = "project.updated")]
    ProjectUpdated,
    #[serde(rename = "server.instance.disposed")]
    ServerInstanceDisposed,
    #[serde(rename = "file.edited")]
    FileEdited,
    #[serde(rename = "lsp.client.diagnostics")]
    LspClientDiagnostics,
    #[serde(rename = "todo.updated")]
    TodoUpdated,
    #[serde(rename = "session.status")]
    SessionStatus,
    #[serde(rename = "session.idle")]
    SessionIdle,
    #[serde(rename = "pty.created")]
    PtyCreated,
    #[serde(rename = "pty.updated")]
    PtyUpdated,
    #[serde(rename = "pty.exited")]
    PtyExited,
    #[serde(rename = "pty.deleted")]
    PtyDeleted,
    #[serde(rename = "lsp.updated")]
    LspUpdated,
    #[serde(rename = "mcp.tools.changed")]
    McpToolsChanged,
    #[serde(rename = "file.watcher.updated")]
    FileWatcherUpdated,
    #[serde(rename = "message.updated")]
    MessageUpdated,
    #[serde(rename = "message.removed")]
    MessageRemoved,
    #[serde(rename = "message.part.updated")]
    MessagePartUpdated,
    #[serde(rename = "message.part.removed")]
    MessagePartRemoved,
    #[serde(rename = "permission.updated")]
    PermissionUpdated,
    #[serde(rename = "permission.replied")]
    PermissionReplied,
    #[serde(rename = "command.executed")]
    CommandExecuted,
    #[serde(rename = "vcs.branch.updated")]
    VcsBranchUpdated,
    #[serde(rename = "session.compacted")]
    SessionCompacted,
    #[serde(rename = "session.created")]
    SessionCreated,
    #[serde(rename = "session.updated")]
    SessionUpdated,
    #[serde(rename = "session.deleted")]
    SessionDeleted,
    #[serde(rename = "session.diff")]
    SessionDiff,
    #[serde(rename = "session.error")]
    SessionError,
    #[serde(rename = "server.connected")]
    ServerConnected,
    #[serde(rename = "global.disposed")]
    GlobalDisposed,
}

impl Default for Type {
    fn default() -> Type {
        Self::TuiPromptAppend
    }
}
