/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPtyExitedProperties {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "exitCode")]
    pub exit_code: f64,
}

impl EventPtyExitedProperties {
    pub fn new(id: String, exit_code: f64) -> EventPtyExitedProperties {
        EventPtyExitedProperties {
            id,
            exit_code,
        }
    }
}

