/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventLspClientDiagnosticsProperties {
    #[serde(rename = "serverID")]
    pub server_id: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl EventLspClientDiagnosticsProperties {
    pub fn new(server_id: String, path: String) -> EventLspClientDiagnosticsProperties {
        EventLspClientDiagnosticsProperties { server_id, path }
    }
}
