/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMessageUpdatedProperties {
    #[serde(rename = "info")]
    pub info: Box<models::Message>,
}

impl EventMessageUpdatedProperties {
    pub fn new(info: models::Message) -> EventMessageUpdatedProperties {
        EventMessageUpdatedProperties {
            info: Box::new(info),
        }
    }
}
