/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSessionCompacted {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventSessionIdleProperties>,
}

impl EventSessionCompacted {
    pub fn new(
        r#type: Type,
        properties: models::EventSessionIdleProperties,
    ) -> EventSessionCompacted {
        EventSessionCompacted {
            r#type,
            properties: Box::new(properties),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "session.compacted")]
    SessionCompacted,
}

impl Default for Type {
    fn default() -> Type {
        Self::SessionCompacted
    }
}
