/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventServerInstanceDisposedProperties {
    #[serde(rename = "directory")]
    pub directory: String,
}

impl EventServerInstanceDisposedProperties {
    pub fn new(directory: String) -> EventServerInstanceDisposedProperties {
        EventServerInstanceDisposedProperties { directory }
    }
}
