/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMessagePartUpdatedProperties {
    #[serde(rename = "part")]
    pub part: Box<models::Part>,
    #[serde(rename = "delta", skip_serializing_if = "Option::is_none")]
    pub delta: Option<String>,
}

impl EventMessagePartUpdatedProperties {
    pub fn new(part: models::Part) -> EventMessagePartUpdatedProperties {
        EventMessagePartUpdatedProperties {
            part: Box::new(part),
            delta: None,
        }
    }
}

