/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventGlobalDisposed {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: serde_json::Value,
}

impl EventGlobalDisposed {
    pub fn new(r#type: Type, properties: serde_json::Value) -> EventGlobalDisposed {
        EventGlobalDisposed { r#type, properties }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "global.disposed")]
    GlobalDisposed,
}

impl Default for Type {
    fn default() -> Type {
        Self::GlobalDisposed
    }
}
