/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventTuiCommandExecute {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventTuiCommandExecuteProperties>,
}

impl EventTuiCommandExecute {
    pub fn new(
        r#type: Type,
        properties: models::EventTuiCommandExecuteProperties,
    ) -> EventTuiCommandExecute {
        EventTuiCommandExecute {
            r#type,
            properties: Box::new(properties),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tui.command.execute")]
    TuiCommandExecute,
}

impl Default for Type {
    fn default() -> Type {
        Self::TuiCommandExecute
    }
}
