/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventFileWatcherUpdated {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventFileWatcherUpdatedProperties>,
}

impl EventFileWatcherUpdated {
    pub fn new(
        r#type: Type,
        properties: models::EventFileWatcherUpdatedProperties,
    ) -> EventFileWatcherUpdated {
        EventFileWatcherUpdated {
            r#type,
            properties: Box::new(properties),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file.watcher.updated")]
    FileWatcherUpdated,
}

impl Default for Type {
    fn default() -> Type {
        Self::FileWatcherUpdated
    }
}
