/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSessionDiffProperties {
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "diff")]
    pub diff: Vec<models::FileDiff>,
}

impl EventSessionDiffProperties {
    pub fn new(session_id: String, diff: Vec<models::FileDiff>) -> EventSessionDiffProperties {
        EventSessionDiffProperties { session_id, diff }
    }
}
