/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSessionStatusProperties {
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "status")]
    pub status: Box<models::SessionStatus>,
}

impl EventSessionStatusProperties {
    pub fn new(session_id: String, status: models::SessionStatus) -> EventSessionStatusProperties {
        EventSessionStatusProperties {
            session_id,
            status: Box::new(status),
        }
    }
}
