/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "added")]
    pub added: i32,
    #[serde(rename = "removed")]
    pub removed: i32,
    #[serde(rename = "status")]
    pub status: Status,
}

impl File {
    pub fn new(path: String, added: i32, removed: i32, status: Status) -> File {
        File {
            path,
            added,
            removed,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "added")]
    Added,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "modified")]
    Modified,
}

impl Default for Status {
    fn default() -> Status {
        Self::Added
    }
}

