/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileContentPatchHunksInner {
    #[serde(rename = "oldStart")]
    pub old_start: f64,
    #[serde(rename = "oldLines")]
    pub old_lines: f64,
    #[serde(rename = "newStart")]
    pub new_start: f64,
    #[serde(rename = "newLines")]
    pub new_lines: f64,
    #[serde(rename = "lines")]
    pub lines: Vec<String>,
}

impl FileContentPatchHunksInner {
    pub fn new(
        old_start: f64,
        old_lines: f64,
        new_start: f64,
        new_lines: f64,
        lines: Vec<String>,
    ) -> FileContentPatchHunksInner {
        FileContentPatchHunksInner {
            old_start,
            old_lines,
            new_start,
            new_lines,
            lines,
        }
    }
}
