/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FindText200ResponseInnerPath {
    #[serde(rename = "text")]
    pub text: String,
}

impl FindText200ResponseInnerPath {
    pub fn new(text: String) -> FindText200ResponseInnerPath {
        FindText200ResponseInnerPath { text }
    }
}
