/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FindText200ResponseInnerSubmatchesInner {
    #[serde(rename = "match")]
    pub r#match: Box<models::FindText200ResponseInnerPath>,
    #[serde(rename = "start")]
    pub start: f64,
    #[serde(rename = "end")]
    pub end: f64,
}

impl FindText200ResponseInnerSubmatchesInner {
    pub fn new(r#match: models::FindText200ResponseInnerPath, start: f64, end: f64) -> FindText200ResponseInnerSubmatchesInner {
        FindText200ResponseInnerSubmatchesInner {
            r#match: Box::new(r#match),
            start,
            end,
        }
    }
}

