/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FormatterStatus {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "extensions")]
    pub extensions: Vec<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl FormatterStatus {
    pub fn new(name: String, extensions: Vec<String>, enabled: bool) -> FormatterStatus {
        FormatterStatus {
            name,
            extensions,
            enabled,
        }
    }
}
