/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalHealth200Response {
    #[serde(rename = "healthy")]
    pub healthy: Healthy,
    #[serde(rename = "version")]
    pub version: String,
}

impl GlobalHealth200Response {
    pub fn new(healthy: Healthy, version: String) -> GlobalHealth200Response {
        GlobalHealth200Response { healthy, version }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Healthy {
    #[serde(rename = "true")]
    True,
}

impl Default for Healthy {
    fn default() -> Healthy {
        Self::True
    }
}
