/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KeybindsConfig : Custom keybind configurations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeybindsConfig {
    /// Leader key for keybind combinations
    #[serde(rename = "leader", skip_serializing_if = "Option::is_none")]
    pub leader: Option<String>,
    /// Exit the application
    #[serde(rename = "app_exit", skip_serializing_if = "Option::is_none")]
    pub app_exit: Option<String>,
    /// Open external editor
    #[serde(rename = "editor_open", skip_serializing_if = "Option::is_none")]
    pub editor_open: Option<String>,
    /// List available themes
    #[serde(rename = "theme_list", skip_serializing_if = "Option::is_none")]
    pub theme_list: Option<String>,
    /// Toggle sidebar
    #[serde(rename = "sidebar_toggle", skip_serializing_if = "Option::is_none")]
    pub sidebar_toggle: Option<String>,
    /// Toggle session scrollbar
    #[serde(rename = "scrollbar_toggle", skip_serializing_if = "Option::is_none")]
    pub scrollbar_toggle: Option<String>,
    /// Toggle username visibility
    #[serde(rename = "username_toggle", skip_serializing_if = "Option::is_none")]
    pub username_toggle: Option<String>,
    /// View status
    #[serde(rename = "status_view", skip_serializing_if = "Option::is_none")]
    pub status_view: Option<String>,
    /// Export session to editor
    #[serde(rename = "session_export", skip_serializing_if = "Option::is_none")]
    pub session_export: Option<String>,
    /// Create a new session
    #[serde(rename = "session_new", skip_serializing_if = "Option::is_none")]
    pub session_new: Option<String>,
    /// List all sessions
    #[serde(rename = "session_list", skip_serializing_if = "Option::is_none")]
    pub session_list: Option<String>,
    /// Show session timeline
    #[serde(rename = "session_timeline", skip_serializing_if = "Option::is_none")]
    pub session_timeline: Option<String>,
    /// Fork session from message
    #[serde(rename = "session_fork", skip_serializing_if = "Option::is_none")]
    pub session_fork: Option<String>,
    /// Rename session
    #[serde(rename = "session_rename", skip_serializing_if = "Option::is_none")]
    pub session_rename: Option<String>,
    /// Share current session
    #[serde(rename = "session_share", skip_serializing_if = "Option::is_none")]
    pub session_share: Option<String>,
    /// Unshare current session
    #[serde(rename = "session_unshare", skip_serializing_if = "Option::is_none")]
    pub session_unshare: Option<String>,
    /// Interrupt current session
    #[serde(rename = "session_interrupt", skip_serializing_if = "Option::is_none")]
    pub session_interrupt: Option<String>,
    /// Compact the session
    #[serde(rename = "session_compact", skip_serializing_if = "Option::is_none")]
    pub session_compact: Option<String>,
    /// Scroll messages up by one page
    #[serde(rename = "messages_page_up", skip_serializing_if = "Option::is_none")]
    pub messages_page_up: Option<String>,
    /// Scroll messages down by one page
    #[serde(rename = "messages_page_down", skip_serializing_if = "Option::is_none")]
    pub messages_page_down: Option<String>,
    /// Scroll messages up by half page
    #[serde(
        rename = "messages_half_page_up",
        skip_serializing_if = "Option::is_none"
    )]
    pub messages_half_page_up: Option<String>,
    /// Scroll messages down by half page
    #[serde(
        rename = "messages_half_page_down",
        skip_serializing_if = "Option::is_none"
    )]
    pub messages_half_page_down: Option<String>,
    /// Navigate to first message
    #[serde(rename = "messages_first", skip_serializing_if = "Option::is_none")]
    pub messages_first: Option<String>,
    /// Navigate to last message
    #[serde(rename = "messages_last", skip_serializing_if = "Option::is_none")]
    pub messages_last: Option<String>,
    /// Navigate to next message
    #[serde(rename = "messages_next", skip_serializing_if = "Option::is_none")]
    pub messages_next: Option<String>,
    /// Navigate to previous message
    #[serde(rename = "messages_previous", skip_serializing_if = "Option::is_none")]
    pub messages_previous: Option<String>,
    /// Navigate to last user message
    #[serde(rename = "messages_last_user", skip_serializing_if = "Option::is_none")]
    pub messages_last_user: Option<String>,
    /// Copy message
    #[serde(rename = "messages_copy", skip_serializing_if = "Option::is_none")]
    pub messages_copy: Option<String>,
    /// Undo message
    #[serde(rename = "messages_undo", skip_serializing_if = "Option::is_none")]
    pub messages_undo: Option<String>,
    /// Redo message
    #[serde(rename = "messages_redo", skip_serializing_if = "Option::is_none")]
    pub messages_redo: Option<String>,
    /// Toggle code block concealment in messages
    #[serde(
        rename = "messages_toggle_conceal",
        skip_serializing_if = "Option::is_none"
    )]
    pub messages_toggle_conceal: Option<String>,
    /// Toggle tool details visibility
    #[serde(rename = "tool_details", skip_serializing_if = "Option::is_none")]
    pub tool_details: Option<String>,
    /// List available models
    #[serde(rename = "model_list", skip_serializing_if = "Option::is_none")]
    pub model_list: Option<String>,
    /// Next recently used model
    #[serde(rename = "model_cycle_recent", skip_serializing_if = "Option::is_none")]
    pub model_cycle_recent: Option<String>,
    /// Previous recently used model
    #[serde(
        rename = "model_cycle_recent_reverse",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_cycle_recent_reverse: Option<String>,
    /// Next favorite model
    #[serde(
        rename = "model_cycle_favorite",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_cycle_favorite: Option<String>,
    /// Previous favorite model
    #[serde(
        rename = "model_cycle_favorite_reverse",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_cycle_favorite_reverse: Option<String>,
    /// List available commands
    #[serde(rename = "command_list", skip_serializing_if = "Option::is_none")]
    pub command_list: Option<String>,
    /// List agents
    #[serde(rename = "agent_list", skip_serializing_if = "Option::is_none")]
    pub agent_list: Option<String>,
    /// Next agent
    #[serde(rename = "agent_cycle", skip_serializing_if = "Option::is_none")]
    pub agent_cycle: Option<String>,
    /// Previous agent
    #[serde(
        rename = "agent_cycle_reverse",
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_cycle_reverse: Option<String>,
    /// Cycle model variants
    #[serde(rename = "variant_cycle", skip_serializing_if = "Option::is_none")]
    pub variant_cycle: Option<String>,
    /// Clear input field
    #[serde(rename = "input_clear", skip_serializing_if = "Option::is_none")]
    pub input_clear: Option<String>,
    /// Paste from clipboard
    #[serde(rename = "input_paste", skip_serializing_if = "Option::is_none")]
    pub input_paste: Option<String>,
    /// Submit input
    #[serde(rename = "input_submit", skip_serializing_if = "Option::is_none")]
    pub input_submit: Option<String>,
    /// Insert newline in input
    #[serde(rename = "input_newline", skip_serializing_if = "Option::is_none")]
    pub input_newline: Option<String>,
    /// Move cursor left in input
    #[serde(rename = "input_move_left", skip_serializing_if = "Option::is_none")]
    pub input_move_left: Option<String>,
    /// Move cursor right in input
    #[serde(rename = "input_move_right", skip_serializing_if = "Option::is_none")]
    pub input_move_right: Option<String>,
    /// Move cursor up in input
    #[serde(rename = "input_move_up", skip_serializing_if = "Option::is_none")]
    pub input_move_up: Option<String>,
    /// Move cursor down in input
    #[serde(rename = "input_move_down", skip_serializing_if = "Option::is_none")]
    pub input_move_down: Option<String>,
    /// Select left in input
    #[serde(rename = "input_select_left", skip_serializing_if = "Option::is_none")]
    pub input_select_left: Option<String>,
    /// Select right in input
    #[serde(rename = "input_select_right", skip_serializing_if = "Option::is_none")]
    pub input_select_right: Option<String>,
    /// Select up in input
    #[serde(rename = "input_select_up", skip_serializing_if = "Option::is_none")]
    pub input_select_up: Option<String>,
    /// Select down in input
    #[serde(rename = "input_select_down", skip_serializing_if = "Option::is_none")]
    pub input_select_down: Option<String>,
    /// Move to start of line in input
    #[serde(rename = "input_line_home", skip_serializing_if = "Option::is_none")]
    pub input_line_home: Option<String>,
    /// Move to end of line in input
    #[serde(rename = "input_line_end", skip_serializing_if = "Option::is_none")]
    pub input_line_end: Option<String>,
    /// Select to start of line in input
    #[serde(
        rename = "input_select_line_home",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_line_home: Option<String>,
    /// Select to end of line in input
    #[serde(
        rename = "input_select_line_end",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_line_end: Option<String>,
    /// Move to start of visual line in input
    #[serde(
        rename = "input_visual_line_home",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_visual_line_home: Option<String>,
    /// Move to end of visual line in input
    #[serde(
        rename = "input_visual_line_end",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_visual_line_end: Option<String>,
    /// Select to start of visual line in input
    #[serde(
        rename = "input_select_visual_line_home",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_visual_line_home: Option<String>,
    /// Select to end of visual line in input
    #[serde(
        rename = "input_select_visual_line_end",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_visual_line_end: Option<String>,
    /// Move to start of buffer in input
    #[serde(rename = "input_buffer_home", skip_serializing_if = "Option::is_none")]
    pub input_buffer_home: Option<String>,
    /// Move to end of buffer in input
    #[serde(rename = "input_buffer_end", skip_serializing_if = "Option::is_none")]
    pub input_buffer_end: Option<String>,
    /// Select to start of buffer in input
    #[serde(
        rename = "input_select_buffer_home",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_buffer_home: Option<String>,
    /// Select to end of buffer in input
    #[serde(
        rename = "input_select_buffer_end",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_buffer_end: Option<String>,
    /// Delete line in input
    #[serde(rename = "input_delete_line", skip_serializing_if = "Option::is_none")]
    pub input_delete_line: Option<String>,
    /// Delete to end of line in input
    #[serde(
        rename = "input_delete_to_line_end",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_delete_to_line_end: Option<String>,
    /// Delete to start of line in input
    #[serde(
        rename = "input_delete_to_line_start",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_delete_to_line_start: Option<String>,
    /// Backspace in input
    #[serde(rename = "input_backspace", skip_serializing_if = "Option::is_none")]
    pub input_backspace: Option<String>,
    /// Delete character in input
    #[serde(rename = "input_delete", skip_serializing_if = "Option::is_none")]
    pub input_delete: Option<String>,
    /// Undo in input
    #[serde(rename = "input_undo", skip_serializing_if = "Option::is_none")]
    pub input_undo: Option<String>,
    /// Redo in input
    #[serde(rename = "input_redo", skip_serializing_if = "Option::is_none")]
    pub input_redo: Option<String>,
    /// Move word forward in input
    #[serde(rename = "input_word_forward", skip_serializing_if = "Option::is_none")]
    pub input_word_forward: Option<String>,
    /// Move word backward in input
    #[serde(
        rename = "input_word_backward",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_word_backward: Option<String>,
    /// Select word forward in input
    #[serde(
        rename = "input_select_word_forward",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_word_forward: Option<String>,
    /// Select word backward in input
    #[serde(
        rename = "input_select_word_backward",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_select_word_backward: Option<String>,
    /// Delete word forward in input
    #[serde(
        rename = "input_delete_word_forward",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_delete_word_forward: Option<String>,
    /// Delete word backward in input
    #[serde(
        rename = "input_delete_word_backward",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_delete_word_backward: Option<String>,
    /// Previous history item
    #[serde(rename = "history_previous", skip_serializing_if = "Option::is_none")]
    pub history_previous: Option<String>,
    /// Next history item
    #[serde(rename = "history_next", skip_serializing_if = "Option::is_none")]
    pub history_next: Option<String>,
    /// Next child session
    #[serde(
        rename = "session_child_cycle",
        skip_serializing_if = "Option::is_none"
    )]
    pub session_child_cycle: Option<String>,
    /// Previous child session
    #[serde(
        rename = "session_child_cycle_reverse",
        skip_serializing_if = "Option::is_none"
    )]
    pub session_child_cycle_reverse: Option<String>,
    /// Go to parent session
    #[serde(rename = "session_parent", skip_serializing_if = "Option::is_none")]
    pub session_parent: Option<String>,
    /// Suspend terminal
    #[serde(rename = "terminal_suspend", skip_serializing_if = "Option::is_none")]
    pub terminal_suspend: Option<String>,
    /// Toggle terminal title
    #[serde(
        rename = "terminal_title_toggle",
        skip_serializing_if = "Option::is_none"
    )]
    pub terminal_title_toggle: Option<String>,
    /// Toggle tips on home screen
    #[serde(rename = "tips_toggle", skip_serializing_if = "Option::is_none")]
    pub tips_toggle: Option<String>,
}

impl KeybindsConfig {
    /// Custom keybind configurations
    pub fn new() -> KeybindsConfig {
        KeybindsConfig {
            leader: None,
            app_exit: None,
            editor_open: None,
            theme_list: None,
            sidebar_toggle: None,
            scrollbar_toggle: None,
            username_toggle: None,
            status_view: None,
            session_export: None,
            session_new: None,
            session_list: None,
            session_timeline: None,
            session_fork: None,
            session_rename: None,
            session_share: None,
            session_unshare: None,
            session_interrupt: None,
            session_compact: None,
            messages_page_up: None,
            messages_page_down: None,
            messages_half_page_up: None,
            messages_half_page_down: None,
            messages_first: None,
            messages_last: None,
            messages_next: None,
            messages_previous: None,
            messages_last_user: None,
            messages_copy: None,
            messages_undo: None,
            messages_redo: None,
            messages_toggle_conceal: None,
            tool_details: None,
            model_list: None,
            model_cycle_recent: None,
            model_cycle_recent_reverse: None,
            model_cycle_favorite: None,
            model_cycle_favorite_reverse: None,
            command_list: None,
            agent_list: None,
            agent_cycle: None,
            agent_cycle_reverse: None,
            variant_cycle: None,
            input_clear: None,
            input_paste: None,
            input_submit: None,
            input_newline: None,
            input_move_left: None,
            input_move_right: None,
            input_move_up: None,
            input_move_down: None,
            input_select_left: None,
            input_select_right: None,
            input_select_up: None,
            input_select_down: None,
            input_line_home: None,
            input_line_end: None,
            input_select_line_home: None,
            input_select_line_end: None,
            input_visual_line_home: None,
            input_visual_line_end: None,
            input_select_visual_line_home: None,
            input_select_visual_line_end: None,
            input_buffer_home: None,
            input_buffer_end: None,
            input_select_buffer_home: None,
            input_select_buffer_end: None,
            input_delete_line: None,
            input_delete_to_line_end: None,
            input_delete_to_line_start: None,
            input_backspace: None,
            input_delete: None,
            input_undo: None,
            input_redo: None,
            input_word_forward: None,
            input_word_backward: None,
            input_select_word_forward: None,
            input_select_word_backward: None,
            input_delete_word_forward: None,
            input_delete_word_backward: None,
            history_previous: None,
            history_next: None,
            session_child_cycle: None,
            session_child_cycle_reverse: None,
            session_parent: None,
            terminal_suspend: None,
            terminal_title_toggle: None,
            tips_toggle: None,
        }
    }
}
