/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LayoutConfig : @deprecated Always uses stretch layout.
/// @deprecated Always uses stretch layout.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LayoutConfig {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "stretch")]
    Stretch,

}

impl std::fmt::Display for LayoutConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Auto => write!(f, "auto"),
            Self::Stretch => write!(f, "stretch"),
        }
    }
}

impl Default for LayoutConfig {
    fn default() -> LayoutConfig {
        Self::Auto
    }
}

