/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpStatusConnected {
    #[serde(rename = "status")]
    pub status: Status,
}

impl McpStatusConnected {
    pub fn new(status: Status) -> McpStatusConnected {
        McpStatusConnected { status }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "connected")]
    Connected,
}

impl Default for Status {
    fn default() -> Status {
        Self::Connected
    }
}
