/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpOAuthConfig {
    /// OAuth client ID. If not provided, dynamic client registration (RFC 7591) will be attempted.
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// OAuth client secret (if required by the authorization server)
    #[serde(rename = "clientSecret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// OAuth scopes to request during authorization
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl McpOAuthConfig {
    pub fn new() -> McpOAuthConfig {
        McpOAuthConfig {
            client_id: None,
            client_secret: None,
            scope: None,
        }
    }
}

