/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpAuthRemove200Response {
    #[serde(rename = "success")]
    pub success: Success,
}

impl McpAuthRemove200Response {
    pub fn new(success: Success) -> McpAuthRemove200Response {
        McpAuthRemove200Response { success }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Success {
    #[serde(rename = "true")]
    True,
}

impl Default for Success {
    fn default() -> Success {
        Self::True
    }
}
