/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpAddRequestConfig {
    /// Type of MCP server connection
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Command and arguments to run the MCP server
    #[serde(rename = "command")]
    pub command: Vec<String>,
    /// Environment variables to set when running the MCP server
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<std::collections::HashMap<String, String>>,
    /// Enable or disable the MCP server on startup
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Timeout in ms for fetching tools from the MCP server. Defaults to 5000 (5 seconds) if not specified.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
    /// URL of the remote MCP server (only for remote type)
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Headers to send with the request
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "oauth", skip_serializing_if = "Option::is_none")]
    pub oauth: Option<Box<models::McpRemoteConfigOauth>>,
}

impl McpAddRequestConfig {
    pub fn new(r#type: Type, command: Vec<String>, url: Option<String>) -> McpAddRequestConfig {
        McpAddRequestConfig {
            r#type,
            command,
            environment: None,
            enabled: None,
            timeout: None,
            url,
            headers: None,
            oauth: None,
        }
    }

    /// Create a new local MCP config (no URL required)
    pub fn local(command: Vec<String>) -> McpAddRequestConfig {
        McpAddRequestConfig {
            r#type: Type::Local,
            command,
            environment: None,
            enabled: None,
            timeout: None,
            url: None,
            headers: None,
            oauth: None,
        }
    }
}
/// Type of MCP server connection
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "remote")]
    Remote,
}

impl Default for Type {
    fn default() -> Type {
        Self::Local
    }
}

