/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpAuthCallbackRequest {
    /// Authorization code from OAuth callback
    #[serde(rename = "code")]
    pub code: String,
}

impl McpAuthCallbackRequest {
    pub fn new(code: String) -> McpAuthCallbackRequest {
        McpAuthCallbackRequest { code }
    }
}
