/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpStatus {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl McpStatus {
    pub fn new(status: Status) -> McpStatus {
        McpStatus {
            status,
            error: None,
        }
    }
}

/// MCP server connection status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "connected")]
    Connected,
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "needs_auth")]
    NeedsAuth,
    #[serde(rename = "needs_client_registration")]
    NeedsClientRegistration,
}

impl Default for Status {
    fn default() -> Status {
        Self::Connected
    }
}
