/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpRemoteConfig {
    /// Type of MCP server connection
    #[serde(rename = "type")]
    pub r#type: Type,
    /// URL of the remote MCP server
    #[serde(rename = "url")]
    pub url: String,
    /// Enable or disable the MCP server on startup
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Headers to send with the request
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "oauth", skip_serializing_if = "Option::is_none")]
    pub oauth: Option<Box<models::McpRemoteConfigOauth>>,
    /// Timeout in ms for fetching tools from the MCP server. Defaults to 5000 (5 seconds) if not specified.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
}

impl McpRemoteConfig {
    pub fn new(r#type: Type, url: String) -> McpRemoteConfig {
        McpRemoteConfig {
            r#type,
            url,
            enabled: None,
            headers: None,
            oauth: None,
            timeout: None,
        }
    }
}
/// Type of MCP server connection
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "remote")]
    Remote,
}

impl Default for Type {
    fn default() -> Type {
        Self::Remote
    }
}
