/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpAddRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "config")]
    pub config: Box<models::McpAddRequestConfig>,
}

impl McpAddRequest {
    pub fn new(name: String, config: models::McpAddRequestConfig) -> McpAddRequest {
        McpAddRequest {
            name,
            config: Box::new(config),
        }
    }
}
