/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpStatusNeedsAuth {
    #[serde(rename = "status")]
    pub status: Status,
}

impl McpStatusNeedsAuth {
    pub fn new(status: Status) -> McpStatusNeedsAuth {
        McpStatusNeedsAuth { status }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "needs_auth")]
    NeedsAuth,
}

impl Default for Status {
    fn default() -> Status {
        Self::NeedsAuth
    }
}
