/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpLocalConfig {
    /// Type of MCP server connection
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Command and arguments to run the MCP server
    #[serde(rename = "command")]
    pub command: Vec<String>,
    /// Environment variables to set when running the MCP server
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<std::collections::HashMap<String, String>>,
    /// Enable or disable the MCP server on startup
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Timeout in ms for fetching tools from the MCP server. Defaults to 5000 (5 seconds) if not specified.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
}

impl McpLocalConfig {
    pub fn new(r#type: Type, command: Vec<String>) -> McpLocalConfig {
        McpLocalConfig {
            r#type,
            command,
            environment: None,
            enabled: None,
            timeout: None,
        }
    }
}
/// Type of MCP server connection
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "local")]
    Local,
}

impl Default for Type {
    fn default() -> Type {
        Self::Local
    }
}
