/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageOutputLengthError {
    #[serde(rename = "name")]
    pub name: Name,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

impl MessageOutputLengthError {
    pub fn new(name: Name, data: serde_json::Value) -> MessageOutputLengthError {
        MessageOutputLengthError { name, data }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "MessageOutputLengthError")]
    MessageOutputLengthError,
}

impl Default for Name {
    fn default() -> Name {
        Self::MessageOutputLengthError
    }
}
