/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "time", default, skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<models::AssistantMessageTime>>,
    // UserMessage fields
    #[serde(rename = "summary", default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<serde_json::Value>,
    #[serde(rename = "agent", default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(rename = "model", default, skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::SessionPromptRequestModel>>,
    #[serde(rename = "system", default, skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    #[serde(rename = "tools", default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<std::collections::HashMap<String, bool>>,
    #[serde(rename = "variant", default, skip_serializing_if = "Option::is_none")]
    pub variant: Option<String>,
    // AssistantMessage fields
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::AssistantMessageError>>,
    #[serde(rename = "parentID", default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "modelID", default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(rename = "providerID", default, skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<String>,
    #[serde(rename = "mode", default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "path", default, skip_serializing_if = "Option::is_none")]
    pub path: Option<Box<models::AssistantMessagePath>>,
    #[serde(rename = "cost", default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<f64>,
    #[serde(rename = "tokens", default, skip_serializing_if = "Option::is_none")]
    pub tokens: Option<Box<models::AssistantMessageTokens>>,
    #[serde(rename = "finish", default, skip_serializing_if = "Option::is_none")]
    pub finish: Option<String>,
}

impl Message {
    pub fn new(id: String, session_id: String, role: Role) -> Message {
        Message {
            id,
            session_id,
            role,
            time: None,
            summary: None,
            agent: None,
            model: None,
            system: None,
            tools: None,
            variant: None,
            error: None,
            parent_id: None,
            model_id: None,
            provider_id: None,
            mode: None,
            path: None,
            cost: None,
            tokens: None,
            finish: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default)]
pub enum Role {
    #[default]
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}
