/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "providerID")]
    pub provider_id: String,
    #[serde(rename = "api")]
    pub api: Box<models::ModelApi>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "family", skip_serializing_if = "Option::is_none")]
    pub family: Option<String>,
    #[serde(rename = "capabilities")]
    pub capabilities: Box<models::ModelCapabilities>,
    #[serde(rename = "cost")]
    pub cost: Box<models::ModelCost>,
    #[serde(rename = "limit")]
    pub limit: Box<models::ProviderList200ResponseAllInnerModelsValueLimit>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "options")]
    pub options: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "headers")]
    pub headers: std::collections::HashMap<String, String>,
    #[serde(rename = "release_date")]
    pub release_date: String,
    #[serde(rename = "variants", skip_serializing_if = "Option::is_none")]
    pub variants: Option<
        std::collections::HashMap<String, std::collections::HashMap<String, serde_json::Value>>,
    >,
}

impl Model {
    pub fn new(
        id: String,
        provider_id: String,
        api: models::ModelApi,
        name: String,
        capabilities: models::ModelCapabilities,
        cost: models::ModelCost,
        limit: models::ProviderList200ResponseAllInnerModelsValueLimit,
        status: Status,
        options: std::collections::HashMap<String, serde_json::Value>,
        headers: std::collections::HashMap<String, String>,
        release_date: String,
    ) -> Model {
        Model {
            id,
            provider_id,
            api: Box::new(api),
            name,
            family: None,
            capabilities: Box::new(capabilities),
            cost: Box::new(cost),
            limit: Box::new(limit),
            status,
            options,
            headers,
            release_date,
            variants: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "alpha")]
    Alpha,
    #[serde(rename = "beta")]
    Beta,
    #[serde(rename = "deprecated")]
    Deprecated,
    #[serde(rename = "active")]
    Active,
}

impl Default for Status {
    fn default() -> Status {
        Self::Alpha
    }
}
