/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Part {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "text", default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "synthetic", default, skip_serializing_if = "Option::is_none")]
    pub synthetic: Option<bool>,
    #[serde(rename = "ignored", default, skip_serializing_if = "Option::is_none")]
    pub ignored: Option<bool>,
    #[serde(rename = "time", default, skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<models::UserMessageTime>>,
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "prompt", default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(
        rename = "description",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<String>,
    #[serde(rename = "agent", default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(rename = "command", default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(rename = "mime", default, skip_serializing_if = "Option::is_none")]
    pub mime: Option<String>,
    #[serde(rename = "filename", default, skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "url", default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::AgentPartSource>>,
    #[serde(rename = "callID", default, skip_serializing_if = "Option::is_none")]
    pub call_id: Option<String>,
    #[serde(rename = "tool", default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(rename = "state", default, skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::ToolState>>,
    #[serde(rename = "snapshot", default, skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<String>,
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "cost", default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<f64>,
    #[serde(rename = "tokens", default, skip_serializing_if = "Option::is_none")]
    pub tokens: Option<Box<models::AssistantMessageTokens>>,
    #[serde(rename = "hash", default, skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "files", default, skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<String>>,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "attempt", default, skip_serializing_if = "Option::is_none")]
    pub attempt: Option<f64>,
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ApiError>>,
    #[serde(rename = "auto", default, skip_serializing_if = "Option::is_none")]
    pub auto: Option<bool>,
}

impl Part {
    pub fn new(id: String, session_id: String, message_id: String, r#type: Type) -> Part {
        Part {
            id,
            session_id,
            message_id,
            r#type,
            text: None,
            synthetic: None,
            ignored: None,
            time: None,
            metadata: None,
            prompt: None,
            description: None,
            agent: None,
            command: None,
            mime: None,
            filename: None,
            url: None,
            source: None,
            call_id: None,
            tool: None,
            state: None,
            snapshot: None,
            reason: None,
            cost: None,
            tokens: None,
            hash: None,
            files: None,
            name: None,
            attempt: None,
            error: None,
            auto: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "subtask")]
    Subtask,
    #[serde(rename = "reasoning")]
    Reasoning,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "tool")]
    Tool,
    #[serde(rename = "step-start")]
    StepStart,
    #[serde(rename = "step-finish")]
    StepFinish,
    #[serde(rename = "snapshot")]
    Snapshot,
    #[serde(rename = "patch")]
    Patch,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "retry")]
    Retry,
    #[serde(rename = "compaction")]
    Compaction,
}

impl Default for Type {
    fn default() -> Type {
        Self::Text
    }
}
