/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartAnyOf {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "prompt")]
    pub prompt: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl PartAnyOf {
    pub fn new(id: String, session_id: String, message_id: String, r#type: Type, prompt: String, description: String, agent: String) -> PartAnyOf {
        PartAnyOf {
            id,
            session_id,
            message_id,
            r#type,
            prompt,
            description,
            agent,
            command: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "subtask")]
    Subtask,
}

impl Default for Type {
    fn default() -> Type {
        Self::Subtask
    }
}

