/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Project {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "worktree")]
    pub worktree: String,
    #[serde(rename = "vcs", skip_serializing_if = "Option::is_none")]
    pub vcs: Option<Vcs>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Box<models::ProjectUpdateRequestIcon>>,
    #[serde(rename = "time")]
    pub time: Box<models::ProjectTime>,
}

impl Project {
    pub fn new(id: String, worktree: String, time: models::ProjectTime) -> Project {
        Project {
            id,
            worktree,
            vcs: None,
            name: None,
            icon: None,
            time: Box::new(time),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Vcs {
    #[serde(rename = "git")]
    Git,
}

impl Default for Vcs {
    fn default() -> Vcs {
        Self::Git
    }
}
