/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectTime {
    #[serde(rename = "created", default)]
    pub created: f64,
    #[serde(rename = "updated", default)]
    pub updated: f64,
    #[serde(
        rename = "initialized",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub initialized: Option<f64>,
}

impl ProjectTime {
    pub fn new(created: f64, updated: f64) -> ProjectTime {
        ProjectTime {
            created,
            updated,
            initialized: None,
        }
    }
}
