/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderAuthMethod {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "label")]
    pub label: String,
}

impl ProviderAuthMethod {
    pub fn new(r#type: Type, label: String) -> ProviderAuthMethod {
        ProviderAuthMethod { r#type, label }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "oauth")]
    Oauth,
    #[serde(rename = "api")]
    Api,
}

impl Default for Type {
    fn default() -> Type {
        Self::Oauth
    }
}
