/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200Response {
    #[serde(rename = "all")]
    pub all: Vec<models::ProviderList200ResponseAllInner>,
    #[serde(rename = "default")]
    pub default: std::collections::HashMap<String, String>,
    #[serde(rename = "connected")]
    pub connected: Vec<String>,
}

impl ProviderList200Response {
    pub fn new(
        all: Vec<models::ProviderList200ResponseAllInner>,
        default: std::collections::HashMap<String, String>,
        connected: Vec<String>,
    ) -> ProviderList200Response {
        ProviderList200Response {
            all,
            default,
            connected,
        }
    }
}
