/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderAuthErrorData {
    #[serde(rename = "providerID")]
    pub provider_id: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl ProviderAuthErrorData {
    pub fn new(provider_id: String, message: String) -> ProviderAuthErrorData {
        ProviderAuthErrorData {
            provider_id,
            message,
        }
    }
}

