/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueApi {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "npm", skip_serializing_if = "Option::is_none")]
    pub npm: Option<String>,
}

impl ProviderList200ResponseAllInnerModelsValueApi {
    pub fn new() -> ProviderList200ResponseAllInnerModelsValueApi {
        ProviderList200ResponseAllInnerModelsValueApi {
            id: None,
            url: None,
            npm: None,
        }
    }
}
