/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueCostContextOver200k {
    #[serde(rename = "input")]
    pub input: f64,
    #[serde(rename = "output")]
    pub output: f64,
    #[serde(rename = "cache_read", skip_serializing_if = "Option::is_none")]
    pub cache_read: Option<f64>,
    #[serde(rename = "cache_write", skip_serializing_if = "Option::is_none")]
    pub cache_write: Option<f64>,
}

impl ProviderList200ResponseAllInnerModelsValueCostContextOver200k {
    pub fn new(
        input: f64,
        output: f64,
    ) -> ProviderList200ResponseAllInnerModelsValueCostContextOver200k {
        ProviderList200ResponseAllInnerModelsValueCostContextOver200k {
            input,
            output,
            cache_read: None,
            cache_write: None,
        }
    }
}
