/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderConfigModelsValueInterleaved {
    #[serde(rename = "field")]
    pub field: Field,
}

impl ProviderConfigModelsValueInterleaved {
    pub fn new(field: Field) -> ProviderConfigModelsValueInterleaved {
        ProviderConfigModelsValueInterleaved { field }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Field {
    #[serde(rename = "reasoning_content")]
    ReasoningContent,
    #[serde(rename = "reasoning_details")]
    ReasoningDetails,
}

impl Default for Field {
    fn default() -> Field {
        Self::ReasoningContent
    }
}
