/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderAuthError {
    #[serde(rename = "name")]
    pub name: Name,
    #[serde(rename = "data")]
    pub data: Box<models::ProviderAuthErrorData>,
}

impl ProviderAuthError {
    pub fn new(name: Name, data: models::ProviderAuthErrorData) -> ProviderAuthError {
        ProviderAuthError {
            name,
            data: Box::new(data),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "ProviderAuthError")]
    ProviderAuthError,
}

impl Default for Name {
    fn default() -> Name {
        Self::ProviderAuthError
    }
}
