/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueProvider {
    #[serde(rename = "npm")]
    pub npm: String,
}

impl ProviderList200ResponseAllInnerModelsValueProvider {
    pub fn new(npm: String) -> ProviderList200ResponseAllInnerModelsValueProvider {
        ProviderList200ResponseAllInnerModelsValueProvider { npm }
    }
}
