/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Provider {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source")]
    pub source: Source,
    #[serde(rename = "env")]
    pub env: Vec<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "options")]
    pub options: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "models")]
    pub models: std::collections::HashMap<String, models::Model>,
}

impl Provider {
    pub fn new(
        id: String,
        name: String,
        source: Source,
        env: Vec<String>,
        options: std::collections::HashMap<String, serde_json::Value>,
        models: std::collections::HashMap<String, models::Model>,
    ) -> Provider {
        Provider {
            id,
            name,
            source,
            env,
            key: None,
            options,
            models,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "env")]
    Env,
    #[serde(rename = "config")]
    Config,
    #[serde(rename = "custom")]
    Custom,
    #[serde(rename = "api")]
    Api,
}

impl Default for Source {
    fn default() -> Source {
        Self::Env
    }
}
