/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderOauthAuthorizeRequest {
    /// Auth method index
    #[serde(rename = "method")]
    pub method: f64,
}

impl ProviderOauthAuthorizeRequest {
    pub fn new(method: f64) -> ProviderOauthAuthorizeRequest {
        ProviderOauthAuthorizeRequest { method }
    }
}
