/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueModalities {
    #[serde(rename = "input")]
    pub input: Vec<Input>,
    #[serde(rename = "output")]
    pub output: Vec<Output>,
}

impl ProviderList200ResponseAllInnerModelsValueModalities {
    pub fn new(input: Vec<Input>, output: Vec<Output>) -> ProviderList200ResponseAllInnerModelsValueModalities {
        ProviderList200ResponseAllInnerModelsValueModalities {
            input,
            output,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Input {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "pdf")]
    Pdf,
}

impl Default for Input {
    fn default() -> Input {
        Self::Text
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Output {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "pdf")]
    Pdf,
}

impl Default for Output {
    fn default() -> Output {
        Self::Text
    }
}

