/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueCapabilities {
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<bool>,
    #[serde(rename = "reasoning", skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<bool>,
    #[serde(rename = "attachment", skip_serializing_if = "Option::is_none")]
    pub attachment: Option<bool>,
    #[serde(rename = "toolcall", skip_serializing_if = "Option::is_none")]
    pub toolcall: Option<bool>,
    #[serde(rename = "interleaved", skip_serializing_if = "Option::is_none")]
    pub interleaved: Option<serde_json::Value>,
}

impl ProviderList200ResponseAllInnerModelsValueCapabilities {
    pub fn new() -> ProviderList200ResponseAllInnerModelsValueCapabilities {
        ProviderList200ResponseAllInnerModelsValueCapabilities {
            temperature: None,
            reasoning: None,
            attachment: None,
            toolcall: None,
            interleaved: None,
        }
    }
}
