/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pty {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "command")]
    pub command: String,
    #[serde(rename = "args")]
    pub args: Vec<String>,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "pid")]
    pub pid: f64,
}

impl Pty {
    pub fn new(id: String, title: String, command: String, args: Vec<String>, cwd: String, status: Status, pid: f64) -> Pty {
        Pty {
            id,
            title,
            command,
            args,
            cwd,
            status,
            pid,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "exited")]
    Exited,
}

impl Default for Status {
    fn default() -> Status {
        Self::Running
    }
}

