/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PtyUpdateRequestSize {
    #[serde(rename = "rows")]
    pub rows: f64,
    #[serde(rename = "cols")]
    pub cols: f64,
}

impl PtyUpdateRequestSize {
    pub fn new(rows: f64, cols: f64) -> PtyUpdateRequestSize {
        PtyUpdateRequestSize { rows, cols }
    }
}
