/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RangeStart {
    #[serde(rename = "line")]
    pub line: f64,
    #[serde(rename = "character")]
    pub character: f64,
}

impl RangeStart {
    pub fn new(line: f64, character: f64) -> RangeStart {
        RangeStart { line, character }
    }
}
