/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Range {
    #[serde(rename = "start")]
    pub start: Box<models::RangeStart>,
    #[serde(rename = "end")]
    pub end: Box<models::RangeStart>,
}

impl Range {
    pub fn new(start: models::RangeStart, end: models::RangeStart) -> Range {
        Range {
            start: Box::new(start),
            end: Box::new(end),
        }
    }
}
