/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetryPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "attempt")]
    pub attempt: f64,
    #[serde(rename = "error")]
    pub error: Box<models::ApiError>,
    #[serde(rename = "time")]
    pub time: Box<models::UserMessageTime>,
}

impl RetryPart {
    pub fn new(
        id: String,
        session_id: String,
        message_id: String,
        r#type: Type,
        attempt: f64,
        error: models::ApiError,
        time: models::UserMessageTime,
    ) -> RetryPart {
        RetryPart {
            id,
            session_id,
            message_id,
            r#type,
            attempt,
            error: Box::new(error),
            time: Box::new(time),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "retry")]
    Retry,
}

impl Default for Type {
    fn default() -> Type {
        Self::Retry
    }
}
