/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerConfig : Server configuration for opencode serve and web commands
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Port to listen on
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// Hostname to listen on
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    /// Enable mDNS service discovery
    #[serde(rename = "mdns", skip_serializing_if = "Option::is_none")]
    pub mdns: Option<bool>,
    /// Additional domains to allow for CORS
    #[serde(rename = "cors", skip_serializing_if = "Option::is_none")]
    pub cors: Option<Vec<String>>,
}

impl ServerConfig {
    /// Server configuration for opencode serve and web commands
    pub fn new() -> ServerConfig {
        ServerConfig {
            port: None,
            hostname: None,
            mdns: None,
            cors: None,
        }
    }
}

