/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionTime {
    #[serde(rename = "created", default)]
    pub created: f64,
    #[serde(rename = "updated", default)]
    pub updated: f64,
    #[serde(
        rename = "compacting",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub compacting: Option<f64>,
    #[serde(rename = "archived", default, skip_serializing_if = "Option::is_none")]
    pub archived: Option<f64>,
}

impl SessionTime {
    pub fn new(created: f64, updated: f64) -> SessionTime {
        SessionTime {
            created,
            updated,
            compacting: None,
            archived: None,
        }
    }
}
