/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionPromptRequestModel {
    #[serde(rename = "providerID")]
    pub provider_id: String,
    #[serde(rename = "modelID")]
    pub model_id: String,
}

impl SessionPromptRequestModel {
    pub fn new(provider_id: String, model_id: String) -> SessionPromptRequestModel {
        SessionPromptRequestModel {
            provider_id,
            model_id,
        }
    }
}
