/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionStatusAnyOf {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl SessionStatusAnyOf {
    pub fn new(r#type: Type) -> SessionStatusAnyOf {
        SessionStatusAnyOf { r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "idle")]
    Idle,
}

impl Default for Type {
    fn default() -> Type {
        Self::Idle
    }
}
