/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionPrompt200Response {
    #[serde(rename = "info")]
    pub info: Box<models::AssistantMessage>,
    #[serde(rename = "parts")]
    pub parts: Vec<models::Part>,
}

impl SessionPrompt200Response {
    pub fn new(
        info: models::AssistantMessage,
        parts: Vec<models::Part>,
    ) -> SessionPrompt200Response {
        SessionPrompt200Response {
            info: Box::new(info),
            parts,
        }
    }
}
