/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionUpdateRequestTime {
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<f64>,
}

impl SessionUpdateRequestTime {
    pub fn new() -> SessionUpdateRequestTime {
        SessionUpdateRequestTime {
            archived: None,
        }
    }
}

