/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionRevert {
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "partID", skip_serializing_if = "Option::is_none")]
    pub part_id: Option<String>,
    #[serde(rename = "snapshot", skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<String>,
    #[serde(rename = "diff", skip_serializing_if = "Option::is_none")]
    pub diff: Option<String>,
}

impl SessionRevert {
    pub fn new(message_id: String) -> SessionRevert {
        SessionRevert {
            message_id,
            part_id: None,
            snapshot: None,
            diff: None,
        }
    }
}

