/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionMessages200ResponseInner {
    #[serde(rename = "info")]
    pub info: Box<models::Message>,
    #[serde(rename = "parts")]
    pub parts: Vec<models::Part>,
}

impl SessionMessages200ResponseInner {
    pub fn new(info: models::Message, parts: Vec<models::Part>) -> SessionMessages200ResponseInner {
        SessionMessages200ResponseInner {
            info: Box::new(info),
            parts,
        }
    }
}
