/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionPromptRequestPartsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "synthetic", skip_serializing_if = "Option::is_none")]
    pub synthetic: Option<bool>,
    #[serde(rename = "ignored", skip_serializing_if = "Option::is_none")]
    pub ignored: Option<bool>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<models::TextPartTime>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "mime")]
    pub mime: String,
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::AgentPartSource>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "prompt")]
    pub prompt: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl SessionPromptRequestPartsInner {
    pub fn new(r#type: Type, text: String, mime: String, url: String, name: String, prompt: String, description: String, agent: String) -> SessionPromptRequestPartsInner {
        SessionPromptRequestPartsInner {
            id: None,
            r#type,
            text,
            synthetic: None,
            ignored: None,
            time: None,
            metadata: None,
            mime,
            filename: None,
            url,
            source: None,
            name,
            prompt,
            description,
            agent,
            command: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "subtask")]
    Subtask,
}

impl Default for Type {
    fn default() -> Type {
        Self::Text
    }
}

