/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionStatusAnyOf2 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl SessionStatusAnyOf2 {
    pub fn new(r#type: Type) -> SessionStatusAnyOf2 {
        SessionStatusAnyOf2 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "busy")]
    Busy,
}

impl Default for Type {
    fn default() -> Type {
        Self::Busy
    }
}

