/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionSummary {
    #[serde(rename = "additions")]
    pub additions: f64,
    #[serde(rename = "deletions")]
    pub deletions: f64,
    #[serde(rename = "files")]
    pub files: f64,
    #[serde(rename = "diffs", skip_serializing_if = "Option::is_none")]
    pub diffs: Option<Vec<models::FileDiff>>,
}

impl SessionSummary {
    pub fn new(additions: f64, deletions: f64, files: f64) -> SessionSummary {
        SessionSummary {
            additions,
            deletions,
            files,
            diffs: None,
        }
    }
}
