/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStateRunningTime {
    #[serde(rename = "start")]
    pub start: f64,
}

impl ToolStateRunningTime {
    pub fn new(start: f64) -> ToolStateRunningTime {
        ToolStateRunningTime { start }
    }
}
