/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStateRunning {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "time")]
    pub time: Box<models::ToolStateRunningTime>,
}

impl ToolStateRunning {
    pub fn new(
        status: Status,
        input: std::collections::HashMap<String, serde_json::Value>,
        time: models::ToolStateRunningTime,
    ) -> ToolStateRunning {
        ToolStateRunning {
            status,
            input,
            title: None,
            metadata: None,
            time: Box::new(time),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "running")]
    Running,
}

impl Default for Status {
    fn default() -> Status {
        Self::Running
    }
}
