/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStatePending {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "raw")]
    pub raw: String,
}

impl ToolStatePending {
    pub fn new(
        status: Status,
        input: std::collections::HashMap<String, serde_json::Value>,
        raw: String,
    ) -> ToolStatePending {
        ToolStatePending { status, input, raw }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
