/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStateErrorTime {
    #[serde(rename = "start")]
    pub start: f64,
    #[serde(rename = "end")]
    pub end: f64,
}

impl ToolStateErrorTime {
    pub fn new(start: f64, end: f64) -> ToolStateErrorTime {
        ToolStateErrorTime { start, end }
    }
}
