/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolState {
    #[serde(rename = "status", default)]
    pub status: Status,
    #[serde(rename = "input", default, skip_serializing_if = "Option::is_none")]
    pub input: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "raw", default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
    #[serde(rename = "title", default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "time", default, skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<models::ToolStateErrorTime>>,
    #[serde(rename = "output", default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    #[serde(
        rename = "attachments",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attachments: Option<Vec<models::FilePart>>,
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl ToolState {
    pub fn new(status: Status) -> ToolState {
        ToolState {
            status,
            input: None,
            raw: None,
            title: None,
            metadata: None,
            time: None,
            output: None,
            attachments: None,
            error: None,
        }
    }
}
///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Status {
    #[default]
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "error")]
    Error,
}
