/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TuiExecuteCommandRequest {
    #[serde(rename = "command")]
    pub command: String,
}

impl TuiExecuteCommandRequest {
    pub fn new(command: String) -> TuiExecuteCommandRequest {
        TuiExecuteCommandRequest { command }
    }
}
