/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TuiControlNext200Response {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "body", deserialize_with = "Option::deserialize")]
    pub body: Option<serde_json::Value>,
}

impl TuiControlNext200Response {
    pub fn new(path: String, body: Option<serde_json::Value>) -> TuiControlNext200Response {
        TuiControlNext200Response { path, body }
    }
}
