/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMessageSummary {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "diffs")]
    pub diffs: Vec<models::FileDiff>,
}

impl UserMessageSummary {
    pub fn new(diffs: Vec<models::FileDiff>) -> UserMessageSummary {
        UserMessageSummary {
            title: None,
            body: None,
            diffs,
        }
    }
}

