/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMessageTime {
    #[serde(rename = "created", default)]
    pub created: f64,
}

impl UserMessageTime {
    pub fn new(created: f64) -> UserMessageTime {
        UserMessageTime { created }
    }
}
