// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTaskRequest = { title: string, description: string, roadmap_item_id: string | null, };
