// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to generate a roadmap
 */
export type GenerateRoadmapRequest = { 
/**
 * Force regeneration even if roadmap exists
 */
force: boolean, };
