// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoadmapPhaseStatus } from "./RoadmapPhaseStatus";

/**
 * A milestone within a roadmap phase
 */
export type RoadmapMilestone = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Milestone title
 */
title: string, 
/**
 * Milestone description
 */
description: string, 
/**
 * Feature IDs included in this milestone
 */
features: Array<string>, 
/**
 * Milestone status
 */
status: RoadmapPhaseStatus, };
