// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overall status of the roadmap
 */
export type RoadmapStatus = "draft" | "active" | "archived";
