// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoadmapComplexity } from "./RoadmapComplexity";
import type { RoadmapFeatureStatus } from "./RoadmapFeatureStatus";
import type { RoadmapPriority } from "./RoadmapPriority";

/**
 * Statistics about a roadmap
 */
export type RoadmapStats = { total_features: number, total_phases: number, by_priority: { [key in RoadmapPriority]?: number }, by_status: { [key in RoadmapFeatureStatus]?: number }, by_complexity: { [key in RoadmapComplexity]?: number }, };
