// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoadmapGenerationPhase } from "./RoadmapGenerationPhase";

/**
 * Status of roadmap generation
 */
export type RoadmapGenerationStatus = { 
/**
 * Current phase
 */
phase: RoadmapGenerationPhase, 
/**
 * Progress percentage (0-100)
 */
progress: number, 
/**
 * Current message/status
 */
message: string, 
/**
 * Error message if phase is Error
 */
error: string | null, };
