// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of roadmap generation process
 */
export type RoadmapGenerationPhase = "idle" | "analyzing" | "discovering" | "generating" | "complete" | "error";
