// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a roadmap feature
 */
export type RoadmapFeatureStatus = "under_review" | "planned" | "in_progress" | "done";
