// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoadmapComplexity } from "./RoadmapComplexity";
import type { RoadmapFeatureStatus } from "./RoadmapFeatureStatus";
import type { RoadmapImpact } from "./RoadmapImpact";
import type { RoadmapPriority } from "./RoadmapPriority";

/**
 * A feature in the roadmap
 */
export type RoadmapFeature = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Feature title
 */
title: string, 
/**
 * Feature description
 */
description: string, 
/**
 * Rationale - why this feature matters
 */
rationale: string, 
/**
 * Priority (MoSCoW)
 */
priority: RoadmapPriority, 
/**
 * Complexity estimate
 */
complexity: RoadmapComplexity, 
/**
 * Impact estimate
 */
impact: RoadmapImpact, 
/**
 * Phase this feature belongs to
 */
phase_id: string, 
/**
 * Feature IDs this depends on
 */
dependencies: Array<string>, 
/**
 * Current status
 */
status: RoadmapFeatureStatus, 
/**
 * Acceptance criteria
 */
acceptance_criteria: Array<string>, 
/**
 * User stories
 */
user_stories: Array<string>, 
/**
 * Linked task ID (when converted to task)
 */
linked_task_id: string | null, };
