// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Target audience for the product
 */
export type TargetAudience = { 
/**
 * Primary user persona
 */
primary: string, 
/**
 * Secondary user personas
 */
secondary: Array<string>, 
/**
 * Pain points the target audience faces
 */
pain_points: Array<string>, 
/**
 * Goals the target audience wants to achieve
 */
goals: Array<string>, 
/**
 * Usage context (when/where/how they use the product)
 */
usage_context: string | null, };
