// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoadmapFeatureStatus } from "./RoadmapFeatureStatus";
import type { RoadmapPriority } from "./RoadmapPriority";

/**
 * Request to update a feature
 */
export type UpdateFeatureRequest = { status: RoadmapFeatureStatus | null, phase_id: string | null, priority: RoadmapPriority | null, linked_task_id: string | null, };
