// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskSource } from "./AskSource";

export type AskResponse = { answer: string, sources: Array<AskSource>, conversation_id: string, };
