// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BranchStatus = { branch: string, state: string, file_count: number, chunk_count: number, page_count: number, last_indexed_at: string | null, progress_percent: number, error_message: string | null, current_phase: string | null, current_item: string | null, };
