// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckRun = { name: string, status: string, conclusion: string | null, html_url: string | null, };
