// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewCommentResponse } from "./ReviewCommentResponse";

export type CommentsListResponse = { comments: Array<ReviewCommentResponse>, };
