// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompleteAction } from "./CompleteAction";
import type { MergeOptions } from "./MergeOptions";
import type { PrOptions } from "./PrOptions";

export type CompleteTaskRequest = { action: CompleteAction, pr_options: PrOptions | null, merge_options: MergeOptions | null, cleanup_worktree: boolean, };
