// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeResultInfo } from "./MergeResultInfo";
import type { PrInfo } from "./PrInfo";

export type CompleteTaskResponse = { success: boolean, pr: PrInfo | null, merge_result: MergeResultInfo | null, worktree_cleaned: boolean, };
