// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSummary } from "./DiffSummary";

export type CompletePreviewResponse = { task_id: string, branch_name: string, base_branch: string, diff_summary: DiffSummary, suggested_pr_title: string, suggested_pr_body: string, github_available: boolean, has_uncommitted_changes: boolean, };
