// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePrCommentRequest = { path: string, line: number, side: string, body: string, commit_id: string, in_reply_to: bigint | null, };
