// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCommentRequest = { file_path: string, line_start: bigint, line_end: bigint, side: string, content: string, };
