// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of changes in a workspace
 */
export type DiffSummary = { 
/**
 * Number of files changed
 */
files_changed: number, 
/**
 * Number of lines added
 */
additions: number, 
/**
 * Number of lines deleted
 */
deletions: number, };
