// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewFinding } from "./ReviewFinding";

export type FindingsResponse = { findings: Array<ReviewFinding>, summary: string, approved: boolean, exists: boolean, };
