// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity level of a finding
 */
export type FindingSeverity = "error" | "warning" | "info";
