// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FixFindingsRequest = { 
/**
 * IDs of findings to fix, or empty to fix all
 */
finding_ids: Array<string> | null, 
/**
 * If true, fix all findings regardless of finding_ids
 */
fix_all: boolean | null, };
