// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHubSettingsResponse = { 
/**
 * Whether a GitHub token is configured (true if token exists)
 */
has_token: boolean, 
/**
 * Masked token for display (e.g., "ghp_****abcd")
 */
masked_token: string | null, };
