// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexRequest = { branch: string | null, force: boolean | null, mode: string | null, index_only: boolean | null, };
