// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergeResultInfo = { "status": "success", commit_sha: string | null, } | { "status": "conflicts", files: Array<string>, };
