// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model selection for a specific phase
 */
export type ModelSelection = { 
/**
 * Provider ID (e.g., "anthropic", "openai")
 */
provider_id: string, 
/**
 * Model ID (e.g., "claude-sonnet-4-20250514", "gpt-4o")
 */
model_id: string, };
