// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenCodeModel } from "./OpenCodeModel";

export type OpenCodeProvider = { id: string, name: string, models: Array<OpenCodeModel>, };
