// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSelection } from "./ModelSelection";

/**
 * Per-phase model configuration
 */
export type PhaseModels = { 
/**
 * Model for planning phase
 */
planning: ModelSelection | null, 
/**
 * Model for implementation phase
 */
implementation: ModelSelection | null, 
/**
 * Model for review phase
 */
review: ModelSelection | null, 
/**
 * Model for fix phase
 */
fix: ModelSelection | null, };
