// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhaseStatus } from "./PhaseStatus";
import type { PhaseSummary } from "./PhaseSummary";

/**
 * Information about a single implementation phase
 */
export type PhaseInfo = { 
/**
 * Phase number (1-indexed)
 */
number: number, 
/**
 * Phase title
 */
title: string, 
/**
 * Phase content from the plan
 */
content: string, 
/**
 * Current status of this phase
 */
status: PhaseStatus, 
/**
 * Associated session ID (if started)
 */
session_id: string | null, 
/**
 * Summary of completed phase
 */
summary: PhaseSummary | null, };
