// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhaseInfo } from "./PhaseInfo";

/**
 * Response for phases endpoint
 */
export type PhasesResponse = { 
/**
 * Whether this task has multiple phases
 */
is_multi_phase: boolean, 
/**
 * Total number of phases
 */
total_phases: number, 
/**
 * Current phase being executed (1-indexed), None if not started or completed
 */
current_phase: number | null, 
/**
 * List of all phases with their status
 */
phases: Array<PhaseInfo>, };
