// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhaseModels } from "./PhaseModels";

export type PhaseModelsResponse = { phase_models: PhaseModels, };
