// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a completed implementation phase
 */
export type PhaseSummary = { 
/**
 * Phase number that was completed
 */
phase_number: number, 
/**
 * Phase title
 */
title: string, 
/**
 * Summary of what was done
 */
summary: string, 
/**
 * List of files that were changed
 */
files_changed: Array<string>, 
/**
 * Notes for the next phase (important context)
 */
notes: string | null, 
/**
 * When the phase was completed
 */
completed_at: string, };
