// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrIssueComment } from "./PrIssueComment";
import type { PrReviewComment } from "./PrReviewComment";

export type PrCommentsResponse = { review_comments: Array<PrReviewComment>, issue_comments: Array<PrIssueComment>, };
