// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrFile } from "./PrFile";

export type PrDiffResponse = { diff: string, files: Array<PrFile>, };
