// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";

export type PrFile = { filename: string, status: FileStatus, additions: number, deletions: number, changes: number, patch: string | null, previous_filename: string | null, };
