// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubUser } from "./GitHubUser";
import type { Reactions } from "./Reactions";

export type PrIssueComment = { id: bigint, body: string, user: GitHubUser, created_at: string, updated_at: string, html_url: string, reactions: Reactions | null, };
