// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhaseModels } from "./PhaseModels";
import type { RoadmapConfig } from "./RoadmapConfig";
import type { UserMode } from "./UserMode";
import type { WikiConfig } from "./WikiConfig";

/**
 * Project-level configuration stored in .opencode-studio/config.json
 */
export type ProjectConfig = { phase_models: PhaseModels, user_mode: UserMode, wiki: WikiConfig, roadmap: RoadmapConfig, };
