// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrOptions = { title: string, body: string, base_branch: string, draft: boolean, };
