// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubUser } from "./GitHubUser";
import type { ReviewState } from "./ReviewState";

export type PrReview = { id: bigint, user: GitHubUser, state: ReviewState, body: string | null, submitted_at: string | null, html_url: string, };
