// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestDetail } from "./PullRequestDetail";

export type PullRequestsListResponse = { pull_requests: Array<PullRequestDetail>, };
