// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Reactions = { total_count: number, "+1": number, "-1": number, laugh: number, hooray: number, confused: number, heart: number, rocket: number, eyes: number, };
