// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewCommentResponse = { id: string, task_id: string, file_path: string, line_start: bigint, line_end: bigint, side: string, content: string, status: string, created_at: bigint, };
