// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingSeverity } from "./FindingSeverity";
import type { FindingStatus } from "./FindingStatus";

/**
 * A single review finding
 */
export type ReviewFinding = { id: string, file_path: string | null, line_start: number | null, line_end: number | null, title: string, description: string, severity: FindingSeverity, status: FindingStatus, };
