// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoadmapFeature } from "./RoadmapFeature";
import type { RoadmapPhase } from "./RoadmapPhase";
import type { RoadmapStatus } from "./RoadmapStatus";
import type { TargetAudience } from "./TargetAudience";

/**
 * The complete roadmap
 */
export type Roadmap = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Project name
 */
project_name: string, 
/**
 * Roadmap version
 */
version: string, 
/**
 * Product vision statement
 */
vision: string, 
/**
 * Target audience information
 */
target_audience: TargetAudience, 
/**
 * Roadmap phases
 */
phases: Array<RoadmapPhase>, 
/**
 * All features in the roadmap
 */
features: Array<RoadmapFeature>, 
/**
 * Overall roadmap status
 */
status: RoadmapStatus, 
/**
 * Creation timestamp
 */
created_at: string, 
/**
 * Last update timestamp
 */
updated_at: string, };
