// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Complexity level for roadmap features
 */
export type RoadmapComplexity = "low" | "medium" | "high";
