// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Impact level for roadmap features
 */
export type RoadmapImpact = "low" | "medium" | "high";
