// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoadmapMilestone } from "./RoadmapMilestone";
import type { RoadmapPhaseStatus } from "./RoadmapPhaseStatus";

/**
 * A phase in the roadmap (e.g., Foundation, Enhancement, Scale)
 */
export type RoadmapPhase = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Phase name
 */
name: string, 
/**
 * Phase description
 */
description: string, 
/**
 * Order in the roadmap (1-based)
 */
order: number, 
/**
 * Phase status
 */
status: RoadmapPhaseStatus, 
/**
 * Feature IDs in this phase
 */
features: Array<string>, 
/**
 * Milestones within this phase
 */
milestones: Array<RoadmapMilestone>, };
