// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Roadmap } from "./Roadmap";
import type { RoadmapStats } from "./RoadmapStats";

export type RoadmapResponse = { roadmap: Roadmap | null, exists: boolean, stats: RoadmapStats | null, };
