// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Priority level for roadmap features (MoSCoW method)
 */
export type RoadmapPriority = "must" | "should" | "could" | "wont";
