// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a roadmap phase
 */
export type RoadmapPhaseStatus = "planned" | "in_progress" | "completed";
