// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceCitationResponse = { file_path: string, start_line: number | null, end_line: number | null, };
