// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";
import type { TaskStatus } from "./TaskStatus";

export type TransitionResponse = { task: Task, previous_status: TaskStatus, };
