// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateGitHubTokenRequest = { 
/**
 * The GitHub personal access token. Set to null or empty string to remove.
 */
token: string | null, };
