// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserMode } from "./UserMode";

export type UpdateUserModeRequest = { mode: UserMode, };
