// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSelection } from "./ModelSelection";

export type UpdatePhaseModelsRequest = { planning: ModelSelection | null, implementation: ModelSelection | null, review: ModelSelection | null, fix: ModelSelection | null, };
