// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateWikiSettingsRequest = { enabled: boolean | null, branches: Array<string> | null, openrouter_api_key: string | null, embedding_model: string | null, chat_model: string | null, auto_sync: boolean | null, repo_url: string | null, access_token: string | null, };
