// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceCitationResponse } from "./SourceCitationResponse";

export type WikiPageResponse = { slug: string, title: string, content: string, page_type: string, parent_slug: string | null, file_paths: Array<string>, has_diagrams: boolean, updated_at: string, importance: string, related_pages: Array<string>, section_id: string | null, source_citations: Array<SourceCitationResponse>, };
