// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WikiSectionResponse } from "./WikiSectionResponse";
import type { WikiTreeNode } from "./WikiTreeNode";

export type WikiStructureResponse = { branch: string, root: WikiTreeNode, page_count: number, sections: Array<WikiSectionResponse>, };
