// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WikiSectionResponse = { id: string, title: string, description: string | null, page_slugs: Array<string>, order: number, };
