// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WikiSettingsResponse = { enabled: boolean, branches: Array<string>, has_api_key: boolean, embedding_model: string | null, chat_model: string | null, auto_sync: boolean, repo_url: string | null, has_access_token: boolean, };
