// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WikiTreeNode = { slug: string, title: string, page_type: string, order: number, children: Array<WikiTreeNode>, };
