// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wiki feature configuration
 */
export type WikiConfig = { 
/**
 * Whether wiki feature is enabled
 */
enabled: boolean, 
/**
 * Branches to index (e.g., ["main", "develop"])
 */
branches: Array<string>, 
/**
 * OpenRouter API key for embeddings and chat
 */
openrouter_api_key: string | null, 
/**
 * Embedding model (default: "openai/text-embedding-3-small")
 */
embedding_model: string | null, 
/**
 * Chat model for RAG (default: "anthropic/claude-3.5-sonnet")
 */
chat_model: string | null, 
/**
 * Auto-sync on git push webhook
 */
auto_sync: boolean, 
/**
 * Remote repository URL for indexing external repos
 */
repo_url: string | null, 
/**
 * Access token for private repositories
 */
access_token: string | null, };
