// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WikiSearchResult = { file_path: string, start_line: number, end_line: number, content: string, language: string | null, score: number, };
