// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WikiSearchResult } from "./WikiSearchResult";

export type WikiSearchResponse = { query: string, results: Array<WikiSearchResult>, total_count: number, duration_ms: bigint, };
