// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceResponse = { task_id: string, path: string, branch_name: string, status: string, created_at: string, };
