// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentMessageData = { 
/**
 * The message content
 */
content: string, 
/**
 * Message role (assistant, user, system)
 */
role: string, 
/**
 * Whether this is a partial/streaming message
 */
is_partial: boolean, };
